Revert "updated ajax gallery"
This reverts commit 3fb70b165c7db9dde38abccef2f7e34a7f183f9c.

git push orin mainerror: src refspec main does not match any
error: failed to push some refs to 'https://github.com/Shibin-jay/tasks.git'
error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/Shibin-jay/tasks.git'